# Using Pint with NumPy

This notebook demonstrates how to use Pint with NumPy for handling units in scientific calculations.

## Setup

First, let's import NumPy and Pint and create a unit registry:

In [1]:
from __future__ import annotations

import numpy as np
np.set_printoptions(precision=2)
import pint
from pint import *

# Create a unit registry
ureg = pint.UnitRegistry()
# Define a shorthand for creating quantities
Q_ = ureg.Quantity

# Silence NEP 18 warning
import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    Q_([])

## Basic Operations with NumPy Arrays

You can apply units to NumPy arrays and perform calculations while maintaining unit consistency:

In [2]:
# Create a NumPy array with units
distances = np.array([10, 20, 30]) * ureg.meter
print(f"Distances: {distances}")

# Create another array with different units
more_distances = np.array([50, 150, 250]) * ureg.centimeter
print(f"More distances: {more_distances}")

# Convert to consistent units
more_distances_m = more_distances.to(ureg.meter)
print(f"More distances in meters: {more_distances_m}")

Distances: [10 20 30] meter
More distances: [ 50 150 250] centimeter
More distances in meters: [0.5 1.5 2.5] meter


## Mathematical Operations

Pint handles unit conversions automatically when performing mathematical operations:

In [3]:
# Addition of arrays with units
# Pint will convert units automatically
total_distance = distances[0:3] + more_distances
print(f"Total distance: {total_distance}")

# Multiplication and division
areas = distances * more_distances_m[0:4]
print(f"Areas: {areas}")

# Unit conversion
areas_cm2 = areas.to(ureg.centimeter**2)
print(f"Areas in cm²: {areas_cm2}")

Total distance: [10.5 21.5 32.5] meter
Areas: [5.0 30.0 75.0] meter ** 2
Areas in cm²: [50000.0 300000.0 750000.0] centimeter ** 2


## NumPy Functions with Pint

Most NumPy functions work seamlessly with Pint quantities:

In [4]:
# Statistical operations
print(f"Mean distance: {np.mean(distances)}")
print(f"Maximum distance: {np.max(distances)}")
print(f"Minimum distance: {np.min(distances)}")
print(f"Standard deviation: {np.std(distances)}")

# Array operations
normalized = distances / np.linalg.norm(distances.magnitude)
print(f"Normalized distances: {normalized}")

# Sqrt preserves units appropriately
lengths = np.array([4, 9, 16, 25]) * ureg.meter**2
sqrt_lengths = np.sqrt(lengths)
print(f"Square root of areas: {sqrt_lengths}")

Mean distance: 20.0 meter
Maximum distance: 30 meter
Minimum distance: 10 meter
Standard deviation: 8.16496580927726 meter
Normalized distances: [0.2672612419124244 0.5345224838248488 0.8017837257372731] meter
Square root of areas: [2.0 3.0 4.0 5.0] meter


## Working with Different Physical Quantities

Let's explore more complex examples mixing different physical quantities:

In [5]:
# Time values
times = np.array([2, 4, 6]) * ureg.second

# Calculate velocities
velocities = distances / times
print(f"Velocities: {velocities}")

# Convert to different units
velocities_kmh = velocities.to(ureg.kilometer / ureg.hour)
print(f"Velocities in km/h: {velocities_kmh}")

# Calculate acceleration
accelerations = velocities / times
print(f"Accelerations: {accelerations}")

# Convert to standard units
print(f"Accelerations in standard units: {accelerations.to_base_units()}")

Velocities: [5.0 5.0 5.0] meter / second
Velocities in km/h: [18.0 18.0 18.0] kilometer / hour
Accelerations: [2.5 1.25 0.8333333333333334] meter / second ** 2
Accelerations in standard units: [2.5 1.25 0.8333333333333334] meter / second ** 2


## Array Shape Operations

NumPy's reshape and other array manipulation functions work with Pint quantities:

In [6]:
# Create a 2D array with units
data_2d = np.array([[1, 2, 3], [4, 5, 6]]) * ureg.kilogram
print(f"2D data:\n{data_2d}")

# Reshape
data_flat = data_2d.flatten()
print(f"Flattened data: {data_flat}")

# Reshape back to 2D but different shape
data_reshaped = data_flat.reshape(3, 2)
print(f"Reshaped data:\n{data_reshaped}")

2D data:
[[1 2 3] [4 5 6]] kilogram
Flattened data: [1 2 3 4 5 6] kilogram
Reshaped data:
[[1 2] [3 4] [5 6]] kilogram


## Dimensionality Error Handling

Pint helps catch errors when trying to combine incompatible units:

In [ ]:
# Create some values with different units
masses = np.array([10, 20, 30]) * ureg.kilogram
temperatures = np.array([20, 25, 30]) * ureg.degC

try:
    # This will raise a DimensionalityError
    combined = masses + temperatures
except pint.DimensionalityError as e:
    print(f"Error: {e}")
    
# But we can multiply them
product = masses * temperatures
print(f"Product: {product}")

## Applying NumPy Functions to Quantity Objects

Let's explore more NumPy functions with quantities:

In [8]:
# Create a quantity array
values = np.array([1.1, 2.2, 3.3, 4.4, 5.5]) * ureg.meter

# Round the values
rounded = np.round(values)
print(f"Rounded values: {rounded}")

# Floor and ceiling
print(f"Floor: {np.floor(values)}")
print(f"Ceiling: {np.ceil(values)}")

# Cumulative sum
cumsum = np.cumsum(values)
print(f"Cumulative sum: {cumsum}")

Rounded values: [1.0 2.0 3.0 4.0 6.0] meter
Floor: [1.0 2.0 3.0 4.0 5.0] meter
Ceiling: [2.0 3.0 4.0 5.0 6.0] meter
Cumulative sum: [1.1 3.3000000000000003 6.6 11.0 16.5] meter


## Converting Between Units

Pint makes it easy to convert between compatible units:

In [21]:
L=180*ureg.inch

isinstance(L, Quantity)
L.to_base_units()

True

In [9]:
# Create some values in different units
lengths = np.array([10, 20, 30, 40, 50]) * ureg.inch
print(f"Original lengths: {lengths}")

# Convert to various units
print(f"In meters: {lengths.to(ureg.meter)}")
print(f"In centimeters: {lengths.to(ureg.centimeter)}")
print(f"In feet: {lengths.to(ureg.foot)}")
print(f"In yards: {lengths.to(ureg.yard)}")

Original lengths: [10 20 30 40 50] inch
In meters: [0.254 0.508 0.762 1.016 1.27] meter
In centimeters: [25.4 50.8 76.2 101.6 127.0] centimeter
In feet: [0.8333333333333333 1.6666666666666665 2.5 3.333333333333333 4.166666666666666] foot
In yards: [0.2777777777777778 0.5555555555555556 0.8333333333333333 1.1111111111111112 1.3888888888888888] yard


## Scientific Calculations Example: Kinetic Energy

Let's calculate the kinetic energy of moving objects using Pint and NumPy:

In [ ]:
# Define masses and velocities
masses = np.array([1, 2, 3, 4, 5]) * ureg.kilogram
velocities = np.array([10, 15, 20, 25, 30]) * ureg.meter / ureg.second

# Calculate kinetic energy: KE = 1/2 * m * v²
kinetic_energies = 0.5 * masses * velocities**2
print(f"Kinetic energies: {kinetic_energies}")

In [13]:
kinetic_energies.to_base_units()

<Quantity([  50.  225.  600. 1250. 2250.], 'kilogram * meter ** 2 / second ** 2')>

In [16]:
# Filter the dir() output to show only attributes from pint-related classes
# This will show methods and attributes inherited from pint's classes
[attr for attr in dir(kinetic_energies) if attr in dir(pint.Quantity) or attr in dir(pint.Unit)]


['T',
 'UnitsContainer',
 '_NumpyQuantity__ito_if_needed',
 '__abs__',
 '__add__',
 '__annotations__',
 '__array__',
 '__array_function__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__copy__',
 '__dask_graph__',
 '__dask_keys__',
 '__dask_optimize__',
 '__dask_postcompute__',
 '__dask_postpersist__',
 '__dask_scheduler__',
 '__dask_tokenize__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new_

In [17]:
kinetic_energies.to_preferred_units()

AttributeError: Neither Quantity object nor its magnitude ([  50.  225.  600. 1250. 2250.]) has attribute 'to_preferred_units'

In [11]:
# Convert to different energy units
print(f"In kilojoules: {kinetic_energies.to(ureg.kilojoule)}")
print(f"In kilocalories: {kinetic_energies.to(ureg.kilocalorie)}")
print(f"In BTU: {kinetic_energies.to(ureg.BTU)}")

Kinetic energies: [50.0 225.0 600.0 1250.0 2250.0] kilogram * meter ** 2 / second ** 2
In kilojoules: [0.05 0.225 0.6 1.25 2.25] kilojoule
In kilocalories: [0.011950286806883365 0.053776290630975145 0.14340344168260039 0.29875717017208414 0.5377629063097514] kilocalorie
In BTU: [0.04739084939567189 0.2132588222805235 0.5686901927480627 1.1847712348917971 2.132588222805235] british_thermal_unit


## Practical Example: Data Analysis with Units

Let's perform a simple data analysis task with units:

In [12]:
# Simulate temperature readings in Celsius from different sensors
temps_celsius = np.random.normal(25, 3, size=(4, 5)) * ureg.degC
print(f"Temperature readings (°C):\n{temps_celsius}")

# Convert to Fahrenheit
temps_fahrenheit = temps_celsius.to(ureg.degF)
print(f"\nTemperature readings (°F):\n{temps_fahrenheit}")

# Calculate statistics by sensor (across rows)
mean_temps = np.mean(temps_celsius, axis=1)
std_temps = np.std(temps_celsius, axis=1)

print(f"\nMean temperatures by sensor: {mean_temps}")
print(f"Std. deviation by sensor: {std_temps}")

# Find the sensor with the highest average temperature
hottest_sensor = np.argmax(mean_temps.magnitude)
print(f"\nHottest sensor: {hottest_sensor} with average temperature {mean_temps[hottest_sensor]}")

# Calculate temperature difference from the mean for each reading
deviations = temps_celsius - np.mean(temps_celsius)
print(f"\nDeviations from overall mean:\n{deviations}")

Temperature readings (°C):
[[22.1650519818743 26.82278998010042 25.094234704336177 23.63715294456545  18.680717675834323] [27.94870495284328 23.255052067210283 23.62253997688368  20.912872503395263 21.68603788867442] [23.702626631916164 20.16776136367868 22.85813261057399  26.17176921083624 22.802076290360244] [25.365872839233223 22.773916792981005 32.63578391127237  21.820397415496622 24.084958300878043]] degree_Celsius

Temperature readings (°F):
[[71.89709356737364 80.2810219641807 77.1696224678051 74.54687530021776  65.62529181650173] [82.30766891511784 73.85909372097842 74.52057195839055 69.64317050611139  71.03486819961391] [74.66472793744907 68.30197045462153 73.14463869903311 79.1091845795052  73.04373732264833] [77.65857111061977 72.99305022736579 90.7444110402902 71.2767153478939  75.35292494158041]] degree_Fahrenheit

Mean temperatures by sensor: [23.279989457342133 23.48504147780138 23.140473221473066 25.336185851972253] degree_Celsius
Std. deviation by sensor: [2.770085688